# Generated by Django 5.0 on 2026-08-05 06:54

import uuid
from django.db import migrations, models


def populate_patient_uuids(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    for patient in Patient.objects.filter(uuid__isnull=True).iterator():
        patient.uuid = uuid.uuid4()
        patient.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_archive_reason_patient_archived_at_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_patient_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='patient',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
