# Generated by Django 5.0 on 2026-08-05 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_populate_patient_uuid'),
        ('users', '0003_profile_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicIntakeStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(choices=[('RECEPTION_INTAKE', 'Reception intake'), ('SENT_TO_NURSE', 'Sent to nurse'), ('NURSE_REVIEW', 'Nurse review'), ('APPOINTMENT_SCHEDULED', 'Appointment scheduled'), ('WAITING_FOR_DOCTOR', 'Waiting for doctor'), ('DOCTOR_CONFIRMED', 'Doctor confirmed'), ('IN_CONSULTATION', 'In consultation'), ('ATTENDED', 'Attended'), ('COMPLETED', 'Completed'), ('FOLLOW_UP_REQUIRED', 'Follow-up required'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], max_length=32)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to='users.profile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_appointments', to='users.profile'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('scheduled', 'scheduled'), ('confirmed', 'confirmed'), ('in_consultation', 'in consultation'), ('attended', 'attended'), ('completed', 'completed'), ('missed', 'missed'), ('cancelled', 'cancelled')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='ClinicIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason_for_visit', models.CharField(max_length=255)),
                ('presenting_complaint', models.TextField(max_length=2000)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority'), ('urgent', 'Urgent')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('RECEPTION_INTAKE', 'Reception intake'), ('SENT_TO_NURSE', 'Sent to nurse'), ('NURSE_REVIEW', 'Nurse review'), ('APPOINTMENT_SCHEDULED', 'Appointment scheduled'), ('WAITING_FOR_DOCTOR', 'Waiting for doctor'), ('DOCTOR_CONFIRMED', 'Doctor confirmed'), ('IN_CONSULTATION', 'In consultation'), ('ATTENDED', 'Attended'), ('COMPLETED', 'Completed'), ('FOLLOW_UP_REQUIRED', 'Follow-up required'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], db_index=True, default='RECEPTION_INTAKE', max_length=32)),
                ('scheduling_note', models.TextField(blank=True, max_length=2000)),
                ('follow_up_instructions', models.TextField(blank=True, max_length=3000)),
                ('archive_reason', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(db_index=True, default=False)),
                ('demo_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_intakes', to='users.profile')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_intakes', to='users.profile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intakes', to='users.profile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_intakes', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_intakes', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='intake',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='patients.clinicintake'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['assigned_doctor', 'scheduled_for'], name='patients_ap_assigne_3656f6_idx'),
        ),
        migrations.AddField(
            model_name='clinicintakestatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_status_changes', to='users.profile'),
        ),
        migrations.AddField(
            model_name='clinicintakestatushistory',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='patients.clinicintake'),
        ),
        migrations.AddIndex(
            model_name='clinicintake',
            index=models.Index(fields=['patient', 'status'], name='patients_cl_patient_592798_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicintake',
            index=models.Index(fields=['assigned_doctor', 'status'], name='patients_cl_assigne_ad0a2e_idx'),
        ),
    ]
