# Generated by Django 5.0 on 2026-07-23 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('this_one', models.BooleanField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
            ],
        ),
    ]
