# Generated by Django 5.0 on 2026-08-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_seed_icd_and_map_legacy_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='patient_visible',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
