export const ROLE_CAPABILITIES = {
  AD: {
    displayName: "Doctor-in-Charge / Clinic Administrator",
    portal: "staff",
    defaultRoute: "/clinic-overview",
    responsibility: "Oversee staff, clinic queues, patient workflows and system activity.",
    navigation: [
      ["/clinic-overview", "Clinic Overview", "overview"],
      ["/intakes", "Intake Workflows", "intakes"],
      ["/patients", "Patients", "patients"],
      ["/appointments", "Appointments", "appointments"],
      ["/doctor-queue", "Doctor Queue", "doctor"],
      ["/staff", "Staff Management", "staff"],
      ["/audit-logs", "Audit Logs", "audit"],
      ["/icd-11", "ICD-11", "icd"],
      ["/setup", "System Overview", "settings"],
      ["/account", "Account", "account"],
    ],
    metrics: [
      ["Registered Today", "patients_registered_today", "patients"],
      ["New Intakes", "new_intakes", "intakes"],
      ["Waiting for Nurse", "waiting_for_nurse", "nurse"],
      ["Waiting for Doctor", "waiting_for_doctor", "doctor"],
      ["In Consultation", "in_consultation", "clinical"],
      ["Completed Today", "completed_today", "complete"],
      ["Unassigned Cases", "unassigned_cases", "warning"],
      ["Active Staff", "total_staff", "staff"],
    ],
    actions: ["manage_staff", "view_audit", "reassign", "archive", "clinical_care"],
  },
  DC: {
    displayName: "Doctor",
    portal: "staff",
    defaultRoute: "/doctor-queue",
    responsibility: "Review assigned students and complete clinical consultations.",
    navigation: [
      ["/dashboard", "Dashboard", "dashboard"],
      ["/doctor-queue", "My Queue", "doctor"],
      ["/patients", "Patients", "patients"],
      ["/appointments", "My Appointments", "appointments"],
      ["/icd-11", "ICD-11", "icd"],
      ["/account", "Account", "account"],
    ],
    metrics: [
      ["Assigned Today", "appointments_today", "appointments"],
      ["Waiting", "waiting_for_doctor", "warning"],
      ["Confirmed", "doctor_confirmed", "doctor"],
      ["In Consultation", "in_consultation", "clinical"],
      ["Completed Today", "completed_today", "complete"],
      ["Follow-Up Required", "follow_ups", "followup"],
    ],
    actions: ["confirm", "start", "clinical_care", "complete"],
  },
  NS: {
    displayName: "Nurse",
    portal: "staff",
    defaultRoute: "/nurse-queue",
    responsibility: "Review new intakes and schedule students with available doctors.",
    navigation: [
      ["/dashboard", "Dashboard", "dashboard"],
      ["/nurse-queue", "Intake Queue", "nurse"],
      ["/appointments", "Appointments", "appointments"],
      ["/account", "Account", "account"],
    ],
    metrics: [
      ["New Intakes", "waiting_for_nurse", "intakes"],
      ["Under Review", "under_review", "nurse"],
      ["Needs Appointment", "under_review", "warning"],
      ["Scheduled", "appointments_scheduled", "appointments"],
      ["Waiting for Doctor", "waiting_for_doctor", "doctor"],
      ["Completed Today", "completed_today", "complete"],
    ],
    actions: ["review", "schedule", "reschedule"],
  },
  RC: {
    displayName: "Receptionist",
    portal: "staff",
    defaultRoute: "/reception/intake",
    responsibility: "Register students and send clinic intakes to the nursing queue.",
    navigation: [
      ["/dashboard", "Dashboard", "dashboard"],
      ["/reception/intake", "New Intake", "intakes"],
      ["/patients", "Student Directory", "patients"],
      ["/reception/intakes", "Today's Intakes", "history"],
      ["/appointments", "Appointments", "appointments"],
      ["/account", "Account", "account"],
    ],
    metrics: [
      ["Registered Today", "patients_registered_today", "patients"],
      ["New Intakes", "new_intakes", "intakes"],
      ["Waiting for Nurse", "waiting_for_nurse", "nurse"],
      ["Appointment Scheduled", "appointments_scheduled", "appointments"],
      ["Completed Today", "completed_today", "complete"],
    ],
    actions: ["register_patient", "create_intake", "submit_to_nurse"],
  },
  CO: {
    displayName: "Clinical Officer",
    portal: "staff",
    defaultRoute: "/dashboard",
    responsibility: "Review approved clinic activity within the assigned operational remit.",
    navigation: [
      ["/dashboard", "Dashboard", "dashboard"],
      ["/account", "Account", "account"],
    ],
    metrics: [["Clinic Activity", "visits", "clinical"]],
    actions: ["view_summary"],
  },
  PT: {
    displayName: "Student / Patient",
    portal: "student",
    defaultRoute: "/my-care",
    responsibility: "Track your current clinic visit, appointments and approved health records.",
    navigation: [
      ["/dashboard", "My Dashboard", "dashboard"],
      ["/my-care", "My Care Journey", "journey"],
      ["/my-appointments", "My Appointments", "appointments"],
      ["/my-health-record", "My Health Record", "clinical"],
      ["/account", "Account", "account"],
    ],
    metrics: [
      ["Current Intakes", "new_intakes", "intakes"],
      ["Appointments", "appointments_today", "appointments"],
      ["Visits", "visits", "clinical"],
      ["Follow-Up", "follow_ups", "followup"],
    ],
    actions: ["view_own_care", "refresh_status"],
  },
};

const ROUTE_ACCESS = {
  "/dashboard": ["AD", "DC", "NS", "RC", "CO", "PT"],
  "/clinic-overview": ["AD"],
  "/intakes": ["AD"],
  "/doctor-queue": ["AD", "DC"],
  "/nurse-queue": ["NS"],
  "/reception/intake": ["AD", "RC"],
  "/reception/intakes": ["AD", "RC"],
  "/my-care": ["PT"],
  "/patients": ["AD", "DC", "RC"],
  "/my-health-record": ["PT"],
  "/icd": ["AD", "DC"],
  "/icd-11": ["AD", "DC"],
  "/today-schedule": ["AD", "DC", "NS", "RC", "PT"],
  "/appointments": ["AD", "DC", "NS", "RC"],
  "/my-appointments": ["PT"],
  "/setup": ["AD"],
  "/staff": ["AD"],
  "/audit-logs": ["AD"],
  "/account": ["AD", "DC", "NS", "RC", "CO", "PT"],
};

const UNASSIGNED_ROLE = {
  displayName: "Clinic account",
  portal: "staff",
  defaultRoute: "/dashboard",
  responsibility: "Contact the Doctor-in-Charge to receive an operational clinic role.",
  navigation: [["/dashboard", "Dashboard", "dashboard"], ["/account", "Account", "account"]],
  metrics: [],
  actions: [],
};

export const roleConfig = (role) => ROLE_CAPABILITIES[role] || UNASSIGNED_ROLE;

export const rolesForRoute = (route) => ROUTE_ACCESS[route] || [];

export const roleCan = (role, action) => roleConfig(role).actions.includes(action);
