# Generated by Django 5.0 on 2026-07-23 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('US', 'user'), ('PT', 'patient'), ('DC', 'doctor'), ('NS', 'nurse'), ('RC', 'receptionist'), ('CO', 'coordinator'), ('AD', 'admin')], default='US', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('US', 'user'), ('PT', 'patient'), ('DC', 'doctor'), ('NS', 'nurse'), ('RC', 'receptionist'), ('CO', 'coordinator'), ('AD', 'admin')], default='US', max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(max_length=12)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('departments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('medical_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.medicalfield')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
