# Generated by Django 5.0 on 2026-08-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_must_change_password_profile_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
